---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

I have improved as a student of data science throughout this quarter specifically through this class in R. I think the biggest skills I've improved on were my filtering joins and iteration skills. An example of my growth in filtering joins was from lab 4, and example of my growth in iteration skills was from lab 7. Being a data scientist requires thinking outside of the box, and that was something I struggled to grasp.

I'm submiting Lab 4 for my final portfolio revisions because I feel like I have a lot to demonstrate in terms of what I understand now. When I worked on the lab initially, I used a token to get an extension so I couldn't submit revisions. But I didn't realize at the time Lab 4 was also my heaviest in terms of getting comments back from Dr. Theobold. At first, I wasn't thinking how to use the joins() to filter, but rather, how can I take the existing datasets and just cut those down with filters and selects. My thinking was too straightforward and I wasn't making use of the tools I was taught that week. It felt like a simple task, but I think the part that threw me off the most was Question 2 in Lab 4. I didn't set up the datasets correctly. I had to read through Dr. Theobold's comments to realize that I wasn't even choosing the right metro regions, nor was I making use of the joins to make my work easier. Getting these comments back forced me to reframe my thinking of how I was approaching the problem, and how I could take existing datasets and filter it out with a semi and anti_join(). Setting myself up in this thinking pattern allowed me to move through the rest of revising Lab 4, to use joins() to cut down whenever the instructions called for specifics like getting California cities in Question 6.

In regards to my iteration skills, I chose Lab 7 because I received great feedback after revising it extensively. Unlike Lab 4, I didn't use a token so I had a second chance to improve it. My weakness was redundancy and not making use of the functions. In Part 2 and Question 1 of Lab 7, I wasn't thinking of how to make my function efficient, and I printed lines of code multiple times to run the rescale equation. Receiving feedback from Dr. Theobold helped me realize that I needed to think carefully about my coding actions, and I was able to successfully pass Lab 7. I think growing from Lab 7 helped me in Lab 8 where, minor errors aside, I was able to execute my functions correctly in printing out the 12 days of Christmas.

These artifacts show growth in that I'm taking into consideration constructive criticism and using that to improve my skills as a data scientist. Through revising my errors, I learn from my mistakes and shortcomings. Filtering and iterations and crucial skills to acquire as a data scientist. Joins() is a concept that overlaps with other skills like SQL, and iterations are seen in other languages like Python and Java. My understanding of these two skills have been enhanced and it's changed my thinking towards how to manipulate data.
