---
title: "Lightening Round Essays"
format: html
editor: visual
---

If Bora Joo doesn't earn an A, then nobody should because she's responsible, a team-player, timely, and has background computer science knowledge. Bora Joo is somebody I met through this class and she's one of the friendliest people I've met at Cal Poly. When I got lost on my coding problem and I reached out to her, she was more than happy to help me catch my error and guide me on the right track. From my knowledge, she's also very responsible and gets her work done in a timely manner. I think her background in computer science would help her grasp concepts in R because there's overlap in coding software.

The most difficult part of this class for me were joins. I was really slow to understand the examples that showed the joins graphics to conceptualize how information joined together. I'm not a conceptual person myself, so it was through a lot of practice and revision of Lab 4 that I was able to fully understand joins.

The easiest part of this class for me was creating the ggplots. I'm a visual person, and I enjoy getting creative for my works of art, so ggplots were something I looked forward to everytime it showed up on the assignments. ggplots() also made a lot of sense, in terms of how to overlay aesthetics, what colors/texts we could apply and change. I just worked on ggplot() as I went. It made so much more sense than joins() where I had to figure out my game plan to datasets conceptually before working on it.

The part of the class that surprised me the most was how far I've came through this class. I'm not the strongest or most knowledgable coder, and I didn't feel like I was starting off the quarter strong. When I was compiling all of my assignments, I was just really proud at how nice my visualizations looked, the datasets I filtered/joined/sliced/mutated, and the statistical summaries I was able to pull. It really reinforced a bit of optimism for myself and believing I could potentially head towards the data science field as a business major.

A piece of advice I'd give to a student just beginning a quarter of STAT 331 is to get work in on time. This class is very heavy in terms of contents to grind into us within 10 weeks. I feel like this class took up 70% of my study/homework time because of the amount of time debugging and revising my work. I think this class would've been better during a lighter courseload quarter, but it's doable especially if you have coding experience. There's a certain thinking pattern you will pick up from this class if you haven't gotten it already, to look at data and determine how to manipulate it. Going to office hours is also helpful in keeping you on track, and pinging Dr. Theobold or peers on Discord is the second best thing.
