---
title: "PracticeActivity9.2"
format: html
editor: visual
---

# PRACTICE ACTIVITY 9.2

## Warm Up

```{r}
# 95th percentile for trumpet weight
qunif(0.95, min = 1.5, max = 3.5)

# 10th percentile for trombone weight
qnorm(0.1, mean = 4.6, sd = 0.8)

# percent of trombones more than 5 pounds
pnorm(5, mean = 4.6, sd = 0.8, lower.tail = FALSE)

# percent of reed instruments to be more than 5 pounds
pchisq(5, df = 4, lower.tail = FALSE)

# simulate 100 random trombone weights. below 4 pounds?
sum(rnorm(100, mean = 4.6, sd = 0.8) < 4)
```

## Catching a Con

```{r}
set.seed(1957)

music_man <- function(n_tromb, n_cor, n_reed){
  
  trombones <- rnorm(n_tromb, mean = 4.6, sd = 0.8)
  cornets <- runif(n_cor, min = 1.5, max = 3.5)
  reeds <- rchisq(n_reed, df = 4)
  
  return(sum(trombones, cornets, reeds))
}

my_weights <- map_dbl(.x = 1:1000, 
                      .f = ~ music_man(n_tromb = 76, 
                                       n_cor = 110, 
                                       n_reed = 1035)
                      )
```

```{r}
sum(my_weights < 4532)
```
